version: '2'
services:
    ticketing_system-app:
        image: ticketing_system
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ticketing_system-mysql:3306/ticketing_system?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ticketing_system-elasticsearch:9300
        ports:
            - 8080:8080
    ticketing_system-mysql:
        extends:
            file: mysql.yml
            service: ticketing_system-mysql
    ticketing_system-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ticketing_system-elasticsearch
